import matplotlib.pyplot as plt

from ex9 import nearest_enlarge, compute_entropy, get_highest_loss_month, get_diff_data, \
    get_highest_weight_loss_trainee, load_training_data, Roman

print(Roman('-V'))
print(repr(Roman('-V')))
print(repr(-Roman(50)))
print(repr(-Roman('V')))
print(repr(Roman(5) + Roman(6)))
print(repr(Roman('V') + Roman(6)))
print(repr(Roman(5) + Roman(-6)))
print(repr(Roman('V') + Roman(-6)))
# print(repr(Roman(5) + Roman(-5)))
print(Roman(5) < Roman(6))
print(Roman(6) < Roman(5))
print(Roman(5) > 6)
print(5 < Roman(6))
print(repr(Roman(6) // Roman(5)))
print(repr(Roman('VI') // 5))
print(repr(Roman(6) // Roman('-V')))
print(repr(Roman(6) // -5))
# print(repr(Roman(2) // Roman(3)))
a = load_training_data("weight_input.csv")
print(a["row_names"])
print(a["column_names"])
# print(a["data"])
print(get_highest_weight_loss_trainee(a))
print(get_diff_data(a))
print(get_highest_loss_month(a))
# print(get_relative_diff_table(a))
print(compute_entropy("cameraman.tif"))
b = nearest_enlarge("cameraman.tif", 3)
plt.figure()
plt.imshow(b)
plt.show()
